export const INVOICE_UPDATE = 'INVOICE_UPDATE';

export const UI_CHANGE_LANGUAGE = 'UI_CHANGE_LANGUAGE';

export const SETTINGS_RELOAD_CONFIGS = 'SETTINGS_RELOAD_CONFIGS';
export const SETTINGS_UPDATE_CONFIGS = 'SETTINGS_UPDATE_CONFIGS';

export const SETTINGS_UPDATE_PROFILE = 'SETTINGS_UPDATE_PROFILE';
